--
version: '2.3'
services:
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        restart: unless-stopped
        ports:
            - 7443:9443
            - 7900:9000
        volumes:
            - /home/docker/portainer/ssl:/certs
            - /home/docker/portainer/:/data
        command:
            --ssl
            --sslcert /certs/portainer.crt
            --sslkey /certs/portainer.key